---
- name: Install prerequisites for adding MariaDB repo
  ansible.builtin.apt:
    name:
      - curl
      - software-properties-common
      - apt-transport-https
      - ca-certificates
    state: present
    update_cache: true

- name: Install PyMySQL using pip
  ansible.builtin.pip:
    name: PyMySQL

- name: Download the MariaDB repository setup script
  ansible.builtin.get_url:
    url: "{{ mariadb_repo_setup_url }}"
    dest: /tmp/mariadb_repo_setup
    mode: '0755'

- name: Run the MariaDB repository setup script
  ansible.builtin.command:
    cmd: /tmp/mariadb_repo_setup --mariadb-server-version={{ mariadb_version }}
    creates: /etc/apt/sources.list.d/mariadb.list

- name: Update APT cache after adding MariaDB repo
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install MariaDB server and client
  ansible.builtin.apt:
    name:
      - mariadb-server
      - mariadb-client
    state: present

- name: Configure MariaDB
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
    mode: "0644"
  notify:
    - Restart MariaDB

- name: Ensure MariaDB service is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
