---
- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true
  become: true

- name: Install essential packages
  ansible.builtin.apt:
    name:
      - git
      - python-is-python3
      - python3-dev
      - python3-pip
      - cron
      - curl
      - ca-certificates
      - apt-transport-https
      - redis-server
    state: present
